### ISSUE TITLE
Opera problem, pause on hover not working

### ISSUE THREAD

**Issue by bogdanfer** [jonmifsud/Web-Ticker#23]
Opera Version 12.16
hoverpause: true

and Opera ignores me and keeps scrolling. 

anyone? thanks

**Comment by jonmifsud** [comment]
@bogdanfer I'm not sure if you're still using this with that particular opera version; we've just tested this and it's not an issue anymore on the latest opera version so we are closing the ticket. Let us know if this is still an issue.
